import subprocess
subprocess.check_output(['systemctl', 'is-active', '--quiet', 'jenkins'])  # All that is technically needed...
print(subprocess.check_output(['systemctl', 'is-active', '--quiet', 'jenkins']))